language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
#  - pip install cython
  - pip install git+https://github.com/nakagami/cymysql.git
  - python setup.py install
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.6.11.tar.gz; tar zxf Django-1.6.11.tar.gz)
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.7.7.tar.gz; tar zxf Django-1.7.7.tar.gz)
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.8.tar.gz; tar zxf Django-1.8.tar.gz)
  - cp test_cymysql.py /tmp/Django-1.6.11/tests
  - cp test_cymysql.py /tmp/Django-1.7.7/tests
  - cp test_cymysql.py /tmp/Django-1.8/tests

before_script:
  - mysql -e 'create database test_cymysql DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -e 'create database test_cymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'

script:
  - (cd /tmp/Django-1.6.11/tests; PYTHONPATH='..' python runtests.py --settings=test_cymysql)
  - (cd /tmp/Django-1.7.7/tests; PYTHONPATH='..' python runtests.py --settings=test_cymysql)
  - (cd /tmp/Django-1.8/tests; PYTHONPATH='..' python runtests.py --settings=test_cymysql)
