language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install cython
  - pip install cymysql
  - python setup.py install
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.6.6.tar.gz; tar zxvf Django-1.6.6.tar.gz)
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.7.tar.gz; tar zxvf Django-1.7.tar.gz)
  - cp test_cymysql.py /tmp/Django-1.6.6/tests
  - cp test_cymysql.py /tmp/Django-1.7/tests

before_script:
  - mysql -e 'create database test_cymysql DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -e 'create database test_cymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'

script:
  - PYTHONPATH='/tmp/Django-1.6.6' python /tmp/Django-1.6.6/tests/runtests.py --settings=test_cymysql
  - PYTHONPATH='/tmp/Django-1.7' python /tmp/Django-1.7/tests/runtests.py --settings=test_cymysql
