language: python
python:
  - "2.7"

install:
  - pip install cython
  - pip install cymysql
  - python setup.py install
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.6.2.tar.gz)
  - cp test_cymysql.py /tmp/Django-1.6.2/tests

before_script:
  - mysql -e 'create database test_cymysql DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -e 'create database test_cymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'

script:
  - PYTHONPATH='/tmp/Django-1.6.2' python /tmp/Django-1.6.2/tests/runtests.py --settings=test_cymysql
